# Generated by Django 3.1.2 on 2020-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=2000)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=2000)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'conferences',
            },
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=2000)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'hackathons',
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=200)),
                ('jobURL', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('JobDescription', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=2000)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'interns',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=200)),
                ('jobURL', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('JobDescription', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=2000)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=4000)),
                ('eligibility', models.CharField(max_length=2000)),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'scholarships',
            },
        ),
    ]
