# Generated by Django 3.1.2 on 2020-10-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppcal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='JobDescription',
            new_name='jobDescription',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='JobDescription',
            new_name='jobDescription',
        ),
    ]
