# Generated by Django 3.1.2 on 2020-10-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppcal', '0003_auto_20201023_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
